[package]
name = "ucum-cli"
version = "0.1.0"
edition.workspace = true
description = "UCUM (Unified Code for Units of Measure) command-line interface"

[dependencies]
ucum-core = { path = "../ucum-core" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "octofhir-ucum"
path = "src/main.rs" 