name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish ucum-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish -p octofhir-ucum-core --all-features --no-verify
      - name: Wait for ucum-core to be available
        run: |
          for i in {1..10}; do
            sleep 10
            cargo search ucum-core | grep ucum-core && break
          done
      - name: Publish ucum-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish -p octofhir-ucum-cli --all-features --no-verify 