name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Publish main crate to crates.io
      - name: Publish octofhir-ucum
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish --all-features --no-verify

      # WASM Package Publishing
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version
        id: get_version
        run: |
          # Extract version from Cargo.toml
          echo "VERSION=$(awk -F ' *= *' '/^version *=/ {gsub(/\"/, "", $2); print $2; exit}' Cargo.toml)" >> $GITHUB_OUTPUT

      - name: Build WASM package
        run: |
          wasm-pack build --target web --features wasm

      - name: Update package.json version
        run: |
          cd pkg
          # Update version to match Cargo.toml
          node -e "
            const pkg = require('./package.json');
            pkg.version = '${{ steps.get_version.outputs.VERSION }}';
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Publish WASM to npm
        run: |
          cd pkg
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}